.Dd June 2, 2008
.Dt BGPQ3 8
.Sh NAME
.Nm bgpq3
.Nd bgp filtering automation for cisco and juniper routers
.Sh SYNOPSIS
.Nm bgpq3
.Op Fl h
.Op Fl S Ar sources
.Oo
.Fl E |
.Fl f Ar asnumber |
.Fl G Ar asnumber |
.Fl P
.Oc
.Oo
.Fl 3
.Fl 6
.Fl A
.Oc
.Op Fl R Ar len
OBJECTS
.Op "..."
.Sh DESCRIPTION
The
.Nm 
ultility used to generate Cisco and Juniper prefix-lists, extended
access-lists, policy-statements and as-path lists based on RADB data.
.Pp
The options are as follows: 
.Sh DIAGNOSTICS
When everyting is ok, 
.Nm
generates access-list to standard output and exits with status == 0. 
In case of errors they are printed to stderr and program exits with 
non-zero status. 
.Sh AUTHOR
Alexandre Snarskii, <snar@paranoia.ru>
